### ISSUE TITLE
v2 Android Plugin APIs

### ISSUE THREAD

**Issue by jiechic** [v7lin/fake_cookie_manager#1]
The plugin `fake_cookie_manager` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.

**Comment by droplet-js** [comment]
-_-!!! 妈蛋，Flutter坑爹啊，我那一堆的插件排队升级 ...

**Comment by jiechic** [comment]
> -_-!!! 妈蛋，Flutter坑爹啊，我那一堆的插件排队升级 ...

还好，更新内容不是特别多，改一下套接口。加油，需要PR吗？

**Comment by jiechic** [comment]
我那边也坑爹，升级到1.21，然后发现，add-to-app模式有问题，然后我又回退flutter版本了。

**Comment by droplet-js** [comment]
暂时不用，我正打算改名字，这下一起改了吧

**Comment by jiechic** [comment]
啥时候更新？
