### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by jiechic** [v7lin/fake_cookie_manager#2]
在iOS下面调试引入的想法，发现iOS plugin没有实现注册插件，导致存储cookie和获取cookie失效。
本来不是iOS开发，并不太清楚问题出在哪里。

**Comment by jiechic** [comment]
我弄错了。

**Comment by droplet-js** [comment]
1. 请先跑一下插件里的 example
2. 请检查存储和读取cookie所使用 url 的域名是否一直

**Comment by jiechic** [comment]
我就说一下问题
1、请求存储cookie的域名是http://login.abc.com/xxx/xxx cookie 信息是 domain:*.abc.com
2、请求获取cookie的域名是http://api.abc.com/xxx/xxx ，这里cookie获取不到
3、在Android下，这个状体是正常的，也就是，android的cookiemanager是根据cookie 的domain来匹配是否能够拿到这个cookie
但ios下，是通过存储是带下去的url的域名，也就是login.abc.com来存储cookie，如果不是这个域名请求cookie则不会返回cookie

**Comment by jiechic** [comment]
从理解上来说
1、Android原生的cookie存储，需要url和cookie，url是用来验证cookie的有效性，然后url这个值无效
2、Android原生的cookie获取中，传入url，然后找到匹配用url的domain匹配cookie存储值里面的domain，返回cookie
3、iOS原生存储中，需要url和cookie，然后把url的domain和cookie作为key-value存储
4、iOS原生存储中，传入url，使用url的domain作为key，查询之前所有的value的cookie，不管这些cookie内部数据所使用的是什么domain

感觉是这个逻辑差异导致的。

**Comment by droplet-js** [comment]
> 我就说一下问题
> 1、请求存储cookie的域名是http://login.abc.com/xxx/xxx cookie 信息是 domain:*.abc.com
> 2、请求获取cookie的域名是http://api.abc.com/xxx/xxx ，这里cookie获取不到
> 3、在Android下，这个状体是正常的，也就是，android的cookiemanager是根据cookie 的domain来匹配是否能够拿到这个cookie
> 但ios下，是通过存储是带下去的url的域名，也就是login.abc.com来存储cookie，如果不是这个域名请求cookie则不会返回cookie

请先阅读浏览器 cookie 相关知识。Android/iOS对cookie的存取差异插件，插件这边不作处理

**Comment by jiechic** [comment]
![image](https://user-images.githubusercontent.com/518977/113125310-0ccd9680-9249-11eb-8ff4-834c65535ca6.png)

我构造了新的存储数据以及读取数据，debug到domainMatch的方法时，发现，本应该匹配的域名没有匹配上。导致该cookie没有返回

**Comment by droplet-js** [comment]
😂 cookie.domain的值多了一个 '.'，日了狗了

**Comment by jiechic** [comment]
我用的是 
'clientId=3; expires=Tue, 25-Jan-2022 09:34:00 GMT; Max-Age=25920000; path=/; domain=baidu.com'
以前我在Android调试看到也是有'.'
刚刚调试，在iOS下看到也有这个'.'

感谢修复。坐等新版。

思考一个问题，难道iOS11一下存储的cookie没有这个'.'，然后iOS11以上有这个'.'，意思是，使用不同的存储之后对这个值有一些差异化的内容。

下班半小时了，我就不研究了，我要下班去了。

**Comment by droplet-js** [comment]
已修复
